---
abstract: 'Pure-Perl implementation of scaling LZW'
author:
  - 'Meredith Howard <mhoward@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compress-LZW
requires:
  Exporter: 0
  Moo: 0
  base: 0
  namespace::clean: 0
  strictures: 0
resources:
  bugtracker: https://github.com/merrilymeredith/p5-Compress-LZW/issues
  repository: git://github.com/merrilymeredith/p5-Compress-LZW.git
version: 0.02
